#!/usr/bin/env python3
"""Turn 20 smartphone clips into the LSA smartphone test set.

The brief (LSA p6-p7) asks for 10 gestures x 2 clips x 3 sampled frames = 60 RGB images, each
with a gesture label, a binary hand mask and a box **derived from the mask**, in the original
CW1 folder structure minus the depth directories.

Pipeline
--------
1. **Sample 3 frames per clip, at least 1 second apart** (the original brief's keyframe rule),
   preferring sharp frames: within each candidate window the frame with the highest
   variance-of-Laplacian is taken, so a motion-blurred frame is never chosen when a sharp
   neighbour exists.
2. **Propose a hand mask** with a pluggable backend:
   * ``sam``     - Segment Anything, prompted with a point/box and scored against a hand prior.
   * ``grabcut`` - skin-chroma seed -> GrabCut -> largest component (no download required).
   The proposal is a *proposal*: step 4 exists because it will sometimes be wrong.
3. **Derive the box** as the tight box of the thresholded mask, using the identical definition
   as `tools/pack_dataset.py`, so RealSense and smartphone ground truth are generated by one
   rule and the cross-camera comparison is not confounded by a labelling difference.
4. **Emit a QC contact sheet** (`qc/`) with every mask overlaid and every automatic decision
   flagged against the RealSense reference statistics (`01_DATA.md`): hand area 1.6-4.7 % of the
   image, box aspect ~0.76, centre near (0.45, 0.49), border contact rare. Frames outside those
   bands are marked for manual attention rather than silently accepted.
5. **Accept manual corrections** from a small JSON: a click point to re-prompt, an explicit box,
   or a replacement mask PNG path. Re-run and the corrections are applied.

Nothing here is part of the model. It is annotation tooling, which the brief explicitly
sanctions (LSA p6 "you could use the annotation guide provided in coursework 1 release").

Usage
-----
    python tools/annotate_smartphone.py --videos smartphone_dataset/raw_videos \\
        --out smartphone_dataset/18006111_Shihab --backend grabcut
    # inspect smartphone_dataset/18006111_Shihab/../qc/contact_sheet_*.png, write corrections.json
    python tools/annotate_smartphone.py ... --corrections corrections.json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import cv2
import numpy as np

cv2.setNumThreads(1)          # see src/dataloader.py: cv2's pool is not fork-safe

GESTURES = ["G01_call", "G02_dislike", "G03_like", "G04_ok", "G05_one",
            "G06_palm", "G07_peace", "G08_rock", "G09_stop", "G10_three"]
GESTURE_SET = set(GESTURES)
NAME_RE = re.compile(r"^(G\d{2}_[A-Za-z]+)_?(clip\d{2})\.(mp4|mov|m4v|avi)$", re.IGNORECASE)
# The as-recorded scheme: G<scene>_<gesture>.MOV, e.g. G02_call.MOV is the "call" sign shot
# against background 2. The scene number becomes the clip number, so each gesture ends up with
# one clip per background it was recorded against.
SCENE_RE = re.compile(r"^G(\d{1,2})_([A-Za-z]+)\.(mp4|mov|m4v|avi)$", re.IGNORECASE)
GESTURE_BY_WORD = {g.split("_", 1)[1].lower(): g for g in GESTURES}
EMIT_SIZE = (640, 480)      # the RealSense release's resolution; keeps the two sets comparable
HOLD_WINDOW = (0.20, 0.80)  # sample only the middle of a clip -- see the module docstring
STRIDE = 3                  # 30 fps / 3 = a candidate every 0.1 s, ample for picking a sharp one

# Reference bands from the RealSense release (01_DATA.md s2), used only to FLAG proposals.
REF = {"area_lo": 0.010, "area_hi": 0.075, "aspect_lo": 0.35, "aspect_hi": 1.60,
       "cx_lo": 0.15, "cx_hi": 0.85, "cy_lo": 0.15, "cy_hi": 0.85}
MASK_THRESH = 128


# ======================================================================================
# frame sampling
# ======================================================================================
def sharpness(img: np.ndarray) -> float:
    """Variance of the Laplacian — the standard cheap focus measure."""
    return float(cv2.Laplacian(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), cv2.CV_64F).var())


def sample_frames(path: Path, n: int = 3, min_gap_s: float = 1.0) -> list[tuple[int, np.ndarray]]:
    """Pick ``n`` frames, each the sharpest in its window, streaming rather than buffering.

    The held portion of the clip (HOLD_WINDOW) is split into ``n`` equal windows and the sharpest
    frame of each is kept. Splitting by window guarantees the spacing rule by construction while
    avoiding blur, which a fixed-stride sampler walks straight into.

    Only the running best frame per window is held, because these clips are 4K: buffering one
    decoded 3840x2160 clip costs about 4 GB for three frames of output.
    """
    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise RuntimeError(f"cannot open {path}")
    # iPhone clips carry a display-matrix rotation (these are tagged 180 degrees). OpenCV applies
    # it when ORIENTATION_AUTO is on, and every frame is upside down when it is not -- so set it
    # explicitly and verify below rather than depending on the build's default.
    if hasattr(cv2, "CAP_PROP_ORIENTATION_AUTO"):
        cap.set(cv2.CAP_PROP_ORIENTATION_AUTO, 1)
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    if total <= 0:
        raise RuntimeError(f"cannot determine frame count for {path}")
    lo, hi = int(total * HOLD_WINDOW[0]), int(total * HOLD_WINDOW[1])
    span = max(1, hi - lo)
    if span / fps < min_gap_s * (n - 1):
        print(f"[warn] {path.name}: the held portion is {span / fps:.2f}s, shorter than the "
              f"{min_gap_s * (n - 1):.0f}s the {n}-frame spacing rule needs", file=sys.stderr)

    bounds = np.linspace(lo, hi, n + 1).astype(int)
    best: list[tuple[float, int, np.ndarray] | None] = [None] * n
    # Seek to the held window rather than decoding up to it. H.264 seeking lands on the nearest
    # keyframe, so the true position is read back rather than assumed.
    cap.set(cv2.CAP_PROP_POS_FRAMES, lo)
    idx = int(cap.get(cv2.CAP_PROP_POS_FRAMES) or lo)
    seen = 0
    while idx < hi:
        ok, f = cap.read()
        if not ok:
            break
        if idx >= lo and (idx - lo) % STRIDE == 0:
            w = int(np.searchsorted(bounds, idx, side="right")) - 1
            if 0 <= w < n:
                seen += 1
                sc = sharpness(f)
                if best[w] is None or sc > best[w][0]:
                    best[w] = (sc, idx, f)
        idx += 1
    cap.release()
    if seen == 0:
        raise RuntimeError(f"no frames decoded from {path}")
    picks = [(b[1], b[2]) for b in best if b is not None]
    if len(picks) < n:
        raise RuntimeError(f"{path.name}: only {len(picks)} of {n} windows yielded a frame")
    return picks


def centre_crop_43(img: np.ndarray) -> np.ndarray:
    """Centre-crop to 4:3 if the frame is wider, so phone 16:9 matches the RealSense aspect.

    Width-only crop, which is why the recording guide's framing rule is expressed in terms of
    frame *height*: the height rule survives the crop untouched.
    """
    h, w = img.shape[:2]
    target_w = int(round(h * 4 / 3))
    if w <= target_w:
        return img
    x0 = (w - target_w) // 2
    return img[:, x0:x0 + target_w]


# ======================================================================================
# mask proposal backends
# ======================================================================================
def skin_prior(bgr: np.ndarray) -> np.ndarray:
    """Loose skin-chroma likelihood in YCrCb — a seed, never the final mask.

    Deliberately permissive: the job is to give GrabCut a foreground seed that is mostly hand,
    not to segment the hand. A tight threshold tuned on one skin tone would bias the test set,
    which is exactly the sort of thing the cross-camera experiment must not smuggle in.
    """
    ycrcb = cv2.cvtColor(bgr, cv2.COLOR_BGR2YCrCb)
    cr, cb = ycrcb[..., 1].astype(np.int16), ycrcb[..., 2].astype(np.int16)
    m = ((cr >= 130) & (cr <= 180) & (cb >= 77) & (cb <= 135)).astype(np.uint8)
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    return cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((11, 11), np.uint8))


def largest_component(mask: np.ndarray) -> np.ndarray:
    n, lab, stats, _ = cv2.connectedComponentsWithStats((mask > 0).astype(np.uint8), 8)
    if n <= 1:
        return np.zeros_like(mask, np.uint8)
    k = 1 + int(np.argmax(stats[1:, cv2.CC_STAT_AREA]))
    return ((lab == k).astype(np.uint8)) * 255


def _rect_grabcut(bgr: np.ndarray, rect, iters: int = 5) -> np.ndarray:
    """GrabCut initialised from a rectangle. The fallback that cannot fail for lack of samples."""
    gc = np.zeros(bgr.shape[:2], np.uint8)
    bgd, fgd = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)
    try:
        cv2.grabCut(bgr, gc, tuple(int(v) for v in rect), bgd, fgd, iters, cv2.GC_INIT_WITH_RECT)
    except cv2.error:
        m = np.zeros(bgr.shape[:2], np.uint8)
        x, y, w, h = (int(v) for v in rect)
        m[y:y + h, x:x + w] = 255
        return m
    return np.where((gc == cv2.GC_FGD) | (gc == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)


def propose_grabcut(bgr: np.ndarray, point: tuple[int, int] | None = None,
                    iters: int = 5) -> np.ndarray:
    """Skin seed -> GrabCut -> largest component. No model download required.

    Three guards, each of which fired during testing:

    * **The skin seed is only trusted when it is plausibly hand-sized.** On a background whose
      chroma happens to sit in the skin band the seed can cover the whole frame; the reference
      distribution says a hand is 1-7.5% of the image, so a seed outside [0.2%, 35%] is discarded
      and a centre rectangle is used instead. A seed that covers everything is not a weak signal,
      it is *no* signal, and treating it as one produces a full-frame "hand".
    * **A border ring is always marked sure-background**, unconditionally. `cv2.grabCut` asserts
      on an empty background sample set, so a mask init with no definite background crashes.
    * **A result covering more than half the frame is rejected** in favour of the rectangle
      variant, and if that also fails the frame is left for manual correction rather than shipped.
    """
    h, w = bgr.shape[:2]
    npix = float(h * w)
    centre_rect = (int(w * 0.25), int(h * 0.15), int(w * 0.50), int(h * 0.70))

    seed = largest_component(skin_prior(bgr) * 255)
    frac = float((seed > 0).sum()) / npix
    if not (0.002 <= frac <= 0.35):
        seed = np.zeros((h, w), np.uint8)
        if point is not None:
            cv2.circle(seed, point, max(10, min(h, w) // 12), 255, -1)
        else:
            x, y, rw, rh = centre_rect
            seed[y:y + rh, x:x + rw] = 255
    elif point is not None:
        cv2.circle(seed, point, max(8, min(h, w) // 25), 255, -1)

    gc = np.full((h, w), cv2.GC_PR_BGD, np.uint8)
    sure_fg = cv2.erode(seed, np.ones((15, 15), np.uint8))
    probable = cv2.dilate(seed, np.ones((35, 35), np.uint8))
    gc[probable > 0] = cv2.GC_PR_FGD
    if sure_fg.sum() == 0:                       # erosion can annihilate a thin seed
        sure_fg = seed
    gc[sure_fg > 0] = cv2.GC_FGD
    ring = np.zeros((h, w), np.uint8)
    b = max(6, min(h, w) // 40)
    ring[:b, :] = ring[-b:, :] = ring[:, :b] = ring[:, -b:] = 1
    gc[ring > 0] = cv2.GC_BGD                    # unconditional: grabCut needs bgd samples

    out = None
    if (gc == cv2.GC_FGD).any() and (gc == cv2.GC_BGD).any():
        bgd, fgd = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)
        try:
            cv2.grabCut(bgr, gc, None, bgd, fgd, iters, cv2.GC_INIT_WITH_MASK)
            out = np.where((gc == cv2.GC_FGD) | (gc == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)
        except cv2.error as e:
            print(f"[warn] mask-init grabCut failed ({str(e).splitlines()[-1][:70]}); "
                  f"retrying from a rectangle", file=sys.stderr)

    if out is None or float((out > 0).sum()) / npix > 0.5:
        rect = centre_rect
        if point is not None:
            rw, rh = int(w * 0.34), int(h * 0.52)
            rect = (max(0, point[0] - rw // 2), max(0, point[1] - rh // 2), rw, rh)
        out = _rect_grabcut(bgr, rect, iters)

    out = cv2.morphologyEx(out, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    out = cv2.morphologyEx(out, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))
    return largest_component(out)


_SAM = {}



def background_plate(path, crop_fn=None, emit_size=None, n: int = 12) -> "np.ndarray | None":
    """Per-pixel median of frames from the head and tail of a clip: the empty scene.

    The hand is raised into shot and dropped out again, so the first and last tenth of a clip are
    background. A median over both ends is robust to a few frames that do contain the hand, which
    a mean would not be.
    """
    cap = cv2.VideoCapture(str(path))
    if hasattr(cv2, "CAP_PROP_ORIENTATION_AUTO"):
        cap.set(cv2.CAP_PROP_ORIENTATION_AUTO, 1)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    if total <= 0:
        cap.release(); return None
    head = list(range(0, max(1, int(total * 0.10)), max(1, int(total * 0.10) // (n // 2) or 1)))
    tail = list(range(int(total * 0.90), total, max(1, (total - int(total * 0.90)) // (n // 2) or 1)))
    grabbed = []
    for i in head + tail:
        cap.set(cv2.CAP_PROP_POS_FRAMES, i)
        ok, f = cap.read()
        if not ok:
            continue
        if crop_fn is not None:
            f = crop_fn(f)
        if emit_size and (f.shape[1], f.shape[0]) != emit_size:
            f = cv2.resize(f, emit_size, interpolation=cv2.INTER_AREA)
        grabbed.append(f)
    cap.release()
    if len(grabbed) < 3:
        return None
    return np.median(np.stack(grabbed), axis=0).astype(np.uint8)


def scene_plate(videos, crop_fn=None, emit_size=None, per_clip: int = 3,
                cache: "Path | None" = None) -> "np.ndarray | None":
    """Median across frames from every clip of one scene: the room without the hand.

    Ten gestures share each background and the hand is somewhere different in each, so a pixel is
    covered by the hand in a minority of clips and the median returns the background. This is
    strictly better than a per-clip plate, which fails whenever the hand is in shot for the whole
    clip.
    """
    if cache is not None and cache.exists():
        img = cv2.imread(str(cache))
        if img is not None:
            return img
    grabbed = []
    for v in videos:
        cap = cv2.VideoCapture(str(v))
        if hasattr(cv2, "CAP_PROP_ORIENTATION_AUTO"):
            cap.set(cv2.CAP_PROP_ORIENTATION_AUTO, 1)
        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        if total <= 0:
            cap.release(); continue
        for frac in np.linspace(0.25, 0.75, per_clip):
            cap.set(cv2.CAP_PROP_POS_FRAMES, int(total * frac))
            ok, f = cap.read()
            if not ok:
                continue
            if crop_fn is not None:
                f = crop_fn(f)
            if emit_size and (f.shape[1], f.shape[0]) != emit_size:
                f = cv2.resize(f, emit_size, interpolation=cv2.INTER_AREA)
            grabbed.append(f)
        cap.release()
    if len(grabbed) < 5:
        return None
    plate = np.median(np.stack(grabbed), axis=0).astype(np.uint8)
    if cache is not None:
        cache.parent.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(cache), plate)
    return plate


def propose_bgsub(bgr: np.ndarray, plate: np.ndarray,
                  point: "tuple[int, int] | None" = None) -> np.ndarray:
    """Try increasingly permissive difference levels; keep the first plausible hand.

    REF's area band comes from the RealSense release, so "plausible" means "the size a hand is in
    the data this set is compared against". The first level that lands in the band wins; if none
    does, the largest attempt is returned, because under-segmentation loses fingers whereas
    over-segmentation is visible on the QC sheet and correctable.
    """
    def miss(f):                       # distance outside the band; 0 when inside it
        return max(0.0, REF["area_lo"] - f) + max(0.0, f - REF["area_hi"])

    best, best_miss, best_frac = None, float("inf"), 0.0
    # Shadow-robust first (chroma-weighted), then lightness-sensitive. A dark hand on a light wall
    # is a lightness difference and nothing else; a cast shadow is a lightness difference too,
    # which is why neither weighting can serve alone.
    ladder = [(sc, 0.25) for sc in (0.5, 0.35, 0.25, 0.15)] + \
             [(sc, 1.0) for sc in (0.5, 0.35, 0.25)]
    for scale, lw in ladder:
        out = _bgsub_at(bgr, plate, point, scale, lw)
        frac = float((out >= MASK_THRESH).mean())
        if REF["area_lo"] <= frac <= REF["area_hi"]:
            return out
        # Keep the attempt closest to the band, not the largest. Returning the largest is right
        # for an under-segmented hand and precisely wrong for an over-segmented forearm.
        if miss(frac) < best_miss:
            best, best_miss, best_frac = out, miss(frac), frac

    if best is not None and best_frac < REF["area_lo"] and best.max() > 0:
        # Still too small at every level: the difference has found the hand's position but not its
        # extent. Rectangle-initialised GrabCut over a generous neighbourhood of that position
        # recovers the shape from the image itself.
        ys, xs = np.nonzero(best >= MASK_THRESH)
        h, w = best.shape
        pad = int(0.6 * max(ys.ptp() + 1, xs.ptp() + 1)) + 8
        x1, y1 = max(0, xs.min() - pad), max(0, ys.min() - pad)
        x2, y2 = min(w - 1, xs.max() + pad), min(h - 1, ys.max() + pad)
        if x2 - x1 > 10 and y2 - y1 > 10:
            rect = _rect_grabcut(bgr, (x1, y1, x2 - x1, y2 - y1))
            rf = float((rect >= MASK_THRESH).mean())
            if miss(rf) < best_miss:
                return rect
    return best


def _bgsub_at(bgr: np.ndarray, plate: np.ndarray,
              point: "tuple[int, int] | None", wide_scale: float,
              l_weight: float = 0.25) -> np.ndarray:
    """Hand mask as "what differs from the empty scene", refined by GrabCut.

    The difference is taken in CIE Lab so that a change in illumination alone -- the hand casting
    a shadow on the wall -- moves L without moving a and b, and a chroma-weighted distance keeps
    the shadow out of the mask while keeping the hand in it.
    """
    lab_f = cv2.cvtColor(cv2.GaussianBlur(bgr, (5, 5), 0), cv2.COLOR_BGR2LAB).astype(np.int16)
    lab_p = cv2.cvtColor(cv2.GaussianBlur(plate, (5, 5), 0), cv2.COLOR_BGR2LAB).astype(np.int16)
    # float32, not int16. A Lab difference reaches 255, and 255^2 = 65025 overflows int16 to a
    # NEGATIVE value, so the sqrt below returns NaN and the cast turns it into noise. The effect
    # is that the LARGEST differences -- a dark hand against a bright wall, exactly the case that
    # was failing -- were the ones silently discarded. numpy raised "invalid value encountered in
    # sqrt" about this from the first run; it was a warning on stderr among thousands of lines,
    # and it was the whole problem.
    d = (lab_f - lab_p).astype(np.float32)
    # Chroma weighted 2x against lightness: a cast shadow is a big L change and a small ab change.
    dist = np.sqrt(l_weight * d[..., 0] ** 2 + d[..., 1] ** 2 + d[..., 2] ** 2)
    dist = np.clip(dist, 0, 255).astype(np.uint8)
    t_otsu, core_raw = cv2.threshold(dist, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    # A second, more permissive level. Otsu picks the split that best separates two populations;
    # when the hand and the wall are nearly the same colour that split lands inside the hand and
    # returns a sliver. Half the Otsu level is the candidate region GrabCut is allowed to claim.
    _, wide_raw = cv2.threshold(dist, max(4.0, t_otsu * wide_scale), 255, cv2.THRESH_BINARY)
    k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    clean = lambda m: largest_component(
        cv2.morphologyEx(cv2.morphologyEx(m, cv2.MORPH_OPEN, k, 1), cv2.MORPH_CLOSE, k, 2))
    core_raw, wide_raw = clean(core_raw), clean(wide_raw)
    seed = wide_raw if wide_raw.max() > 0 else core_raw
    if seed.max() == 0:
        return propose_grabcut(bgr, point)

    gc = np.full(bgr.shape[:2], cv2.GC_BGD, np.uint8)
    near = cv2.dilate(seed, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (35, 35)))
    core = cv2.erode(core_raw, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9)))
    gc[near > 0] = cv2.GC_PR_BGD
    gc[seed > 0] = cv2.GC_PR_FGD
    gc[core > 0] = cv2.GC_FGD
    if (gc == cv2.GC_FGD).sum() < 50 or (gc == cv2.GC_BGD).sum() < 50:
        return seed
    try:
        bgd, fgd = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)
        cv2.grabCut(bgr, gc, None, bgd, fgd, 3, cv2.GC_INIT_WITH_MASK)
    except cv2.error:
        return seed
    out = np.where((gc == cv2.GC_FGD) | (gc == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)
    out = largest_component(cv2.morphologyEx(out, cv2.MORPH_CLOSE, k, iterations=2))
    # Absolute sanity, not a multiple of the seed: a seed that is itself a sliver makes "3x the
    # seed" a meaningless ceiling. A hand is never a quarter of the frame.
    frac = (out >= 128).mean()
    if out.sum() == 0 or frac > 0.25:
        return seed
    return out



def cut_at_wrist(mask: np.ndarray, k: float = 1.7) -> np.ndarray:
    """Drop the forearm from a hand-and-arm silhouette entering from a frame edge.

    ``k`` is the cut distance in palm radii below the palm centre. It is deliberately generous:
    keeping a little forearm is a smaller error than amputating fingers, and the QC sheet is
    where the remaining judgement happens.
    """
    m = (mask >= 128).astype(np.uint8)
    if m.sum() == 0:
        return mask
    h, w = m.shape
    touches = {"bottom": m[-1].any(), "top": m[0].any(),
               "left": m[:, 0].any(), "right": m[:, -1].any()}
    if not any(touches.values()):
        return mask                      # already hand-only; nothing to do

    dt = cv2.distanceTransform(m, cv2.DIST_L2, 5)
    if float(dt.max()) < 3:
        return mask

    # Locate the entry point first, then look for the palm in the far half of the blob. A sleeved
    # forearm held horizontally inscribes a larger circle than the hand, so a global argmax puts
    # the "palm" inside the sleeve and the cut then removes the hand instead of the arm.
    edge0 = np.zeros_like(m)
    edge0[0, :] = m[0, :]; edge0[-1, :] = m[-1, :]
    edge0[:, 0] = m[:, 0]; edge0[:, -1] = m[:, -1]
    eys, exs = np.nonzero(edge0)
    if len(eys) == 0:
        return mask
    ey, ex = float(eys.mean()), float(exs.mean())
    gy0, gx0 = np.mgrid[0:h, 0:w]
    from_entry = np.hypot(gy0 - ey, gx0 - ex) * m
    far = from_entry > (0.5 * from_entry.max())
    search = np.where(far, dt, 0.0)
    if search.max() < 3:
        search = dt
    r = float(search.max())
    cy, cx = np.unravel_index(int(np.argmax(search)), search.shape)

    # The arm's direction, from the palm outwards. Taken as palm centre -> centroid of the mask
    # pixels actually lying on a frame border, so an arm entering diagonally or from the side is
    # handled the same as one rising from the bottom. An axis-aligned cut could not do that, and
    # left the sleeve in the mask for every horizontally-held gesture.
    edge = np.zeros_like(m)
    edge[0, :] = m[0, :]; edge[-1, :] = m[-1, :]
    edge[:, 0] = m[:, 0]; edge[:, -1] = m[:, -1]
    ys, xs = np.nonzero(edge)
    if len(ys) == 0:
        return mask
    vy, vx = float(ys.mean() - cy), float(xs.mean() - cx)
    n = float(np.hypot(vy, vx))
    if n < 1e-3:
        return mask
    vy, vx = vy / n, vx / n

    # Keep everything on the palm side of a line perpendicular to that direction, placed k palm
    # radii along it.
    gy, gx = np.mgrid[0:h, 0:w]
    proj = (gy - cy) * vy + (gx - cx) * vx
    cut = (proj <= k * r).astype(np.uint8)
    out = largest_component((m * cut * 255).astype(np.uint8))
    # Conservative: if the cut removed most of the blob, or left nothing, the heuristic did not
    # apply to this shape and the uncut mask is the safer artefact to send to QC.
    if out.sum() == 0 or out.sum() < 0.30 * m.sum() * 255:
        return mask
    return out


def propose_sam(bgr: np.ndarray, ckpt: str, point: tuple[int, int] | None = None) -> np.ndarray:
    """Segment Anything with a point prompt, best of the three returned masks under a hand prior.

    Loaded lazily and cached: the encoder is the expensive part and 60 frames would otherwise
    pay for it 60 times.
    """
    if "predictor" not in _SAM:
        from segment_anything import SamPredictor, sam_model_registry   # optional dependency
        import torch
        kind = "vit_h" if "vit_h" in ckpt else "vit_l" if "vit_l" in ckpt else "vit_b"
        sam = sam_model_registry[kind](checkpoint=ckpt)
        sam.to("cuda" if torch.cuda.is_available() else "cpu")
        _SAM["predictor"] = SamPredictor(sam)
    pred = _SAM["predictor"]
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    pred.set_image(rgb)
    h, w = bgr.shape[:2]
    if point is None:
        sk = skin_prior(bgr)
        ys, xs = np.nonzero(largest_component(sk * 255))
        point = (int(xs.mean()), int(ys.mean())) if xs.size else (w // 2, h // 2)
    masks, scores, _ = pred.predict(point_coords=np.array([point]),
                                    point_labels=np.array([1]), multimask_output=True)
    best, best_s = None, -1e9
    for m, s in zip(masks, scores):
        mm = (m.astype(np.uint8)) * 255
        sc = float(s) + hand_prior_score(mm)
        if sc > best_s:
            best, best_s = mm, sc
    return largest_component(best)


def hand_prior_score(mask: np.ndarray) -> float:
    """Reward proposals that look like the RealSense hand distribution; penalise the rest.

    SAM's own score prefers 'a confident object', which on a hand-and-forearm image is often the
    whole arm. This term is what stops the arm winning.
    """
    h, w = mask.shape
    box = mask_to_box(mask)
    if box is None:
        return -10.0
    x1, y1, x2, y2 = box
    area = float((mask > 0).sum()) / (h * w)
    bw, bh = max(x2 - x1, 1), max(y2 - y1, 1)
    aspect = bw / bh
    cx, cy = (x1 + x2) / 2 / w, (y1 + y2) / 2 / h
    s = 0.0
    s -= 6.0 * max(0.0, REF["area_lo"] - area) / REF["area_lo"]
    s -= 6.0 * max(0.0, area - REF["area_hi"]) / REF["area_hi"]
    s -= 2.0 * max(0.0, REF["aspect_lo"] - aspect) - 2.0 * max(0.0, aspect - REF["aspect_hi"])
    s -= 2.0 * (abs(cx - 0.45) + abs(cy - 0.49))
    fill = float((mask > 0).sum()) / (bw * bh)
    s -= 2.0 * max(0.0, 0.30 - fill)      # a hand fills ~49% of its box; 0.15 means an arm
    return s


def mask_to_box(mask: np.ndarray) -> list[float] | None:
    ys, xs = np.nonzero(mask >= MASK_THRESH)
    if xs.size == 0:
        return None
    return [float(xs.min()), float(ys.min()), float(xs.max() + 1), float(ys.max() + 1)]


# ======================================================================================
# QC
# ======================================================================================
def qc_flags(mask: np.ndarray) -> list[str]:
    h, w = mask.shape
    flags = []
    box = mask_to_box(mask)
    if box is None:
        return ["EMPTY_MASK"]
    x1, y1, x2, y2 = box
    area = float((mask > 0).sum()) / (h * w)
    bw, bh = max(x2 - x1, 1), max(y2 - y1, 1)
    if area < REF["area_lo"]:
        flags.append(f"TOO_SMALL({area * 100:.1f}%)")
    if area > REF["area_hi"]:
        flags.append(f"TOO_LARGE({area * 100:.1f}%)")
    ar = bw / bh
    if not REF["aspect_lo"] <= ar <= REF["aspect_hi"]:
        flags.append(f"ASPECT({ar:.2f})")
    cx, cy = (x1 + x2) / 2 / w, (y1 + y2) / 2 / h
    if not (REF["cx_lo"] <= cx <= REF["cx_hi"] and REF["cy_lo"] <= cy <= REF["cy_hi"]):
        flags.append(f"OFF_CENTRE({cx:.2f},{cy:.2f})")
    if x1 <= 1 or y1 <= 1 or x2 >= w - 1 or y2 >= h - 1:
        flags.append("TOUCHES_BORDER")
    n, _, stats, _ = cv2.connectedComponentsWithStats((mask > 0).astype(np.uint8), 8)
    big = [s for s in stats[1:, cv2.CC_STAT_AREA] if s > 0.005 * h * w]
    if len(big) > 1:
        flags.append(f"MULTI_COMPONENT({len(big)})")
    fill = float((mask > 0).sum()) / (bw * bh)
    if fill < 0.30:
        flags.append(f"LOW_FILL({fill:.2f})")
    return flags


def overlay(bgr: np.ndarray, mask: np.ndarray) -> np.ndarray:
    out = bgr.copy()
    col = np.zeros_like(out)
    col[..., 1] = 255
    m = (mask >= MASK_THRESH)
    out[m] = (0.55 * out[m] + 0.45 * col[m]).astype(np.uint8)
    cnts, _ = cv2.findContours((m).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(out, cnts, -1, (0, 200, 90), 2)
    box = mask_to_box(mask)
    if box:
        x1, y1, x2, y2 = (int(v) for v in box)
        cv2.rectangle(out, (x1, y1), (x2, y2), (0, 215, 255), 2)
    return out


def contact_sheet(items: list[dict], out_path: Path, cols: int = 6, tile: int = 260) -> None:
    rows = int(np.ceil(len(items) / cols))
    sheet = np.full((rows * (tile + 26), cols * tile, 3), 245, np.uint8)
    for i, it in enumerate(items):
        r, c = divmod(i, cols)
        img = cv2.resize(it["overlay"], (tile, tile))
        y0, x0 = r * (tile + 26), c * tile
        sheet[y0 + 26:y0 + 26 + tile, x0:x0 + tile] = img
        bad = bool(it["flags"])
        cv2.rectangle(sheet, (x0, y0), (x0 + tile - 1, y0 + 25),
                      (60, 60, 220) if bad else (230, 230, 230), -1)
        cv2.putText(sheet, it["id"], (x0 + 4, y0 + 11), cv2.FONT_HERSHEY_SIMPLEX, 0.33,
                    (255, 255, 255) if bad else (30, 30, 30), 1, cv2.LINE_AA)
        cv2.putText(sheet, (",".join(it["flags"])[:44] or "ok"), (x0 + 4, y0 + 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.31,
                    (255, 255, 255) if bad else (60, 120, 60), 1, cv2.LINE_AA)
        if bad:
            cv2.rectangle(sheet, (x0, y0 + 26), (x0 + tile - 1, y0 + 25 + tile), (60, 60, 220), 3)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), sheet)


# ======================================================================================
# main
# ======================================================================================
def rebuild_index(out_root: Path, qc_dir: Path, cols: int = 10) -> int:
    """Regenerate boxes.json, annotation_index.json and the contact sheet from the written set."""
    items, index, n_flagged = [], [], 0
    frames = sorted(out_root.glob("G*/clip*/rgb/frame_*.png"))
    for f in frames:
        m = f.parent.parent / "annotation" / f.name
        if not m.exists():
            print(f"[error] no mask for {f}", file=sys.stderr)
            continue
        img = cv2.imread(str(f))
        mask = cv2.imread(str(m), cv2.IMREAD_GRAYSCALE)
        gesture, clip = f.parts[-4], f.parts[-3]
        j = int(f.stem.split("_")[1])
        key = f"{gesture}/{clip}/{j:03d}"
        flags = qc_flags(mask)
        n_flagged += bool(flags)
        index.append({"id": key, "gesture": gesture, "clip": clip, "frame": j,
                      "box": mask_to_box(mask), "flags": flags,
                      "mask_area_frac": round(float((mask >= MASK_THRESH).mean()), 6)})
        items.append({"id": key, "flags": flags, "overlay": overlay(img, mask)})

    boxes = {"convention": "(x1,y1,x2,y2) absolute pixels, tight box of the mask thresholded at "
                          "128; x2/y2 are one past the last foreground pixel, matching "
                          "src/utils.mask_to_box and tools/pack_dataset.py",
             "n": len(index),
             "boxes": {r["id"]: r["box"] for r in index}}
    (out_root / "boxes.json").write_text(json.dumps(boxes, indent=1))
    qc_dir.mkdir(parents=True, exist_ok=True)
    (qc_dir / "annotation_index.json").write_text(json.dumps(index, indent=1))
    for i in range(0, len(items), cols * 6):
        contact_sheet(items[i:i + cols * 6], qc_dir / f"contact_sheet_{i // (cols * 6) + 1:02d}.png",
                      cols=cols)
    print(f"[rebuild] {len(index)} frames, {n_flagged} flagged, "
          f"{len({r['gesture'] for r in index})} gestures, "
          f"{len({(r['gesture'], r['clip']) for r in index})} clips")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--videos", required=True, help="flat folder of 20 clips, G01_call_clip01.mov")
    ap.add_argument("--out", required=True, help="smartphone_dataset/<studentno>_<surname>")
    ap.add_argument("--backend", choices=["grabcut", "sam", "bgsub"], default="bgsub",
                    help="bgsub: difference against a per-clip median background plate, then "
                         "GrabCut refinement. The recorded backgrounds are skin-coloured walls, "
                         "which defeat the chroma seed grabcut relies on.")
    ap.add_argument("--sam-ckpt", default=None)
    ap.add_argument("--frames-per-clip", type=int, default=3)
    ap.add_argument("--rebuild-index", action="store_true",
                    help="regenerate boxes.json and the QC sheet from the frames already written, "
                         "then exit. Resume-safe: derived state is derived from disk.")
    ap.add_argument("--cut-wrist", action="store_true", default=True,
                    help="trim the forearm so masks match the RealSense hand-only convention")
    ap.add_argument("--no-cut-wrist", dest="cut_wrist", action="store_false")
    ap.add_argument("--resume", action="store_true", default=True,
                    help="skip clips whose frames already exist (default on)")
    ap.add_argument("--no-resume", dest="resume", action="store_false")
    ap.add_argument("--max-clips", type=int, default=0,
                    help="stop after this many clips; 0 means all")
    ap.add_argument("--only", default=None,
                    help="comma-separated gesture folders to process, e.g. G01_call,G02_dislike. "
                         "Lets a full regeneration be split across several short runs.")
    ap.add_argument("--scenes", default=None,
                    help="comma-separated scene numbers to include, e.g. 2,3. The brief asks for "
                         "two clips per gesture; three backgrounds were recorded.")
    ap.add_argument("--min-gap-s", type=float, default=1.0)
    ap.add_argument("--crop-43", action="store_true", default=True)
    ap.add_argument("--no-crop-43", dest="crop_43", action="store_false")
    ap.add_argument("--corrections", default=None,
                    help='JSON: {"G01_call/clip01/002": {"point":[x,y]} | {"mask":"path.png"} '
                         '| {"box":[x1,y1,x2,y2]} | {"drop":true}}')
    ap.add_argument("--qc-dir", default=None)
    a = ap.parse_args(argv)

    if a.rebuild_index:
        return rebuild_index(Path(a.out),
                             Path(a.qc_dir) if a.qc_dir else Path(a.out).parent / "qc")

    # Two accepted naming schemes: the guide's <gesture>_clipNN, and the as-recorded
    # G<scene>_<gesture>. They are told apart by whether the word after the number is a gesture.
    def parse(name: str):
        m = NAME_RE.match(name)
        if m and m.group(1) in GESTURE_SET:
            return m.group(1), m.group(2).lower()
        m = SCENE_RE.match(name)
        if m:
            g = GESTURE_BY_WORD.get(m.group(2).lower())
            if g:
                return g, f"clip{int(m.group(1)):02d}"
        return None

    vids = sorted((p for p in Path(a.videos).iterdir() if p.is_file() and parse(p.name)),
                  key=lambda p: (parse(p.name)[0], parse(p.name)[1]))
    if a.only:
        want = {x.strip() for x in a.only.split(",")}
        before = len(vids)
        vids = [v for v in vids if parse(v.name)[0] in want]
        print(f"[ann] gesture filter: {len(vids)} of {before} clips")
    if a.scenes:
        keep = {f"clip{int(x):02d}" for x in a.scenes.split(",")}
        before = len(vids)
        vids = [v for v in vids if parse(v.name)[1] in keep]
        print(f"[ann] scene filter {sorted(keep)}: {len(vids)} of {before} clips")
    if not vids:
        print(f"[error] no correctly-named clips in {a.videos}. Expected G02_call.MOV "
              f"(scene 2, gesture call) or call_clip01.mov.", file=sys.stderr)
        return 2
    corrections = json.loads(Path(a.corrections).read_text()) if a.corrections else {}
    out_root = Path(a.out)
    qc_dir = Path(a.qc_dir) if a.qc_dir else out_root.parent / "qc"
    sheet_items, index, n_flagged = [], [], 0
    scene_plates: dict = {}

    for v in vids:
        gesture, clip = parse(v.name)
        # Resumable: a clip whose frames are already on disk is skipped, so the tool can be run
        # repeatedly until the set is complete without redoing finished work.
        done = out_root / gesture / clip / "rgb"
        if a.resume and len(list(done.glob("frame_*.png"))) >= a.frames_per_clip:
            print(f"[skip] {gesture}/{clip} already written")
            continue
        picks = sample_frames(v, a.frames_per_clip, a.min_gap_s)
        plate = None
        if a.backend == "bgsub":
            # One plate per scene, built from every clip shot against that background.
            if clip not in scene_plates:
                sibs = [x for x in vids if parse(x.name)[1] == clip]
                scene_plates[clip] = scene_plate(
                    sibs, centre_crop_43 if a.crop_43 else None, EMIT_SIZE,
                    cache=qc_dir / f"plate_{clip}.png")
                print(f"[ann] background plate for {clip} from {len(sibs)} clips: "
                      f"{'ok' if scene_plates[clip] is not None else 'FAILED'}")
            plate = scene_plates[clip]
            if plate is None:
                plate = background_plate(v, centre_crop_43 if a.crop_43 else None, EMIT_SIZE)
            if plate is None:
                print(f"[warn] {v.name}: no background plate, falling back to grabcut",
                      file=sys.stderr)
        for j, (fi, frame) in enumerate(picks, start=1):
            if a.crop_43:
                frame = centre_crop_43(frame)
            # Down to the RealSense release's resolution AFTER the crop, so the crop is computed
            # on full detail and the emitted frame matches the set it is compared against.
            if EMIT_SIZE and (frame.shape[1], frame.shape[0]) != EMIT_SIZE:
                frame = cv2.resize(frame, EMIT_SIZE, interpolation=cv2.INTER_AREA)
            key = f"{gesture}/{clip}/{j:03d}"
            corr = corrections.get(key, {})
            if corr.get("drop"):
                print(f"[skip] {key} dropped by corrections file")
                continue

            if "mask" in corr:
                mask = cv2.imread(corr["mask"], cv2.IMREAD_GRAYSCALE)
                mask = np.where(mask >= MASK_THRESH, 255, 0).astype(np.uint8)
            elif "box" in corr:
                x1, y1, x2, y2 = (int(t) for t in corr["box"])
                mask = np.zeros(frame.shape[:2], np.uint8)
                mask[y1:y2, x1:x2] = 255
            else:
                pt = tuple(corr["point"]) if "point" in corr else None
                if a.backend == "sam":
                    if not a.sam_ckpt:
                        print("[error] --backend sam needs --sam-ckpt", file=sys.stderr)
                        return 2
                    mask = propose_sam(frame, a.sam_ckpt, pt)
                elif a.backend == "bgsub" and plate is not None:
                    mask = propose_bgsub(frame, plate, pt)
                else:
                    mask = propose_grabcut(frame, pt)

            # Match the RealSense annotation convention: hand only, forearm excluded. The cut
            # distance is in palm radii, and one value does not serve every pose: a bare hand
            # needs a generous cut, a thick sleeved forearm held horizontally needs a tight one.
            # Tighten until the result is a plausible hand size rather than guessing once.
            if a.cut_wrist:
                for k_try in (1.7, 1.3, 1.0, 0.8, 0.6):
                    cut = cut_at_wrist(mask, k=k_try)
                    if float((cut >= MASK_THRESH).mean()) <= REF["area_hi"]:
                        break
                mask = cut
            flags = qc_flags(mask)
            n_flagged += bool(flags)
            box = mask_to_box(mask)

            cdir = out_root / gesture / clip
            (cdir / "rgb").mkdir(parents=True, exist_ok=True)
            (cdir / "annotation").mkdir(parents=True, exist_ok=True)

            cv2.imwrite(str(cdir / "rgb" / f"frame_{j:03d}.png"), frame)
            cv2.imwrite(str(cdir / "annotation" / f"frame_{j:03d}.png"), mask)

            sheet_items.append({"id": key, "flags": flags, "overlay": overlay(frame, mask)})
            index.append({"id": key, "gesture": gesture, "clip": clip, "frame": j,
                          "source_video": v.name, "source_frame_index": int(fi),
                          "box": box, "flags": flags,
                          "size": [int(frame.shape[1]), int(frame.shape[0])],
                          "backend": ("manual" if ("mask" in corr or "box" in corr)
                                      else a.backend)})
            print(f"[ann] {key:26s} {'FLAG ' + ','.join(flags) if flags else 'ok'}")

    qc_dir.mkdir(parents=True, exist_ok=True)
    for i in range(0, len(sheet_items), 30):
        contact_sheet(sheet_items[i:i + 30], qc_dir / f"contact_sheet_{i // 30 + 1:02d}.png")
    (qc_dir / "annotation_index.json").write_text(json.dumps(index, indent=1))

    # The brief asks for a bounding box "derived from the mask" as part of the dataset itself,
    # so the boxes belong INSIDE the student folder that is handed in -- not only in the QC
    # sidecar, which is working material and is not part of the submitted dataset. The masks
    # remain the source of truth; boxes.json is the derived view, written next to them so a
    # reader does not have to re-derive it to check the annotation.
    boxes = {r["id"]: {"box": r["box"], "gesture": r["gesture"], "clip": r["clip"],
                       "frame": r["frame"], "size": r["size"]} for r in index}
    (out_root / "boxes.json").write_text(json.dumps(
        {"convention": "(x1,y1,x2,y2) absolute pixels, tight box of the mask thresholded at 128; "
                       "x2/y2 are one past the last foreground pixel, matching "
                       "src/utils.mask_to_box and tools/pack_dataset.py",
         "n": len(boxes), "boxes": boxes}, indent=1))

    print(f"\n[ann] {len(index)} frames written to {out_root} (+ boxes.json)")
    print(f"[ann] {n_flagged} flagged for manual review -> {qc_dir}/contact_sheet_*.png")
    if len(index) != 60:
        print(f"[ann] WARNING: the brief asks for 60 frames (10 gestures x 2 clips x 3), got "
              f"{len(index)}", file=sys.stderr)
    missing = sorted(GESTURE_SET - {r['gesture'] for r in index})
    if missing:
        print(f"[ann] WARNING: no clips found for {missing}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
