#!/usr/bin/env python3
"""Turn 20 smartphone clips into the LSA smartphone test set.

The brief (LSA p6-p7) asks for 10 gestures x 2 clips x 3 sampled frames = 60 RGB images, each
with a gesture label, a binary hand mask and a box **derived from the mask**, in the original
CW1 folder structure minus the depth directories.

Pipeline
--------
1. **Sample 3 frames per clip, at least 1 second apart** (the original brief's keyframe rule),
   preferring sharp frames: within each candidate window the frame with the highest
   variance-of-Laplacian is taken, so a motion-blurred frame is never chosen when a sharp
   neighbour exists.
2. **Propose a hand mask** with a pluggable backend:
   * ``sam``     - Segment Anything, prompted with a point/box and scored against a hand prior.
   * ``grabcut`` - skin-chroma seed -> GrabCut -> largest component (no download required).
   The proposal is a *proposal*: step 4 exists because it will sometimes be wrong.
3. **Derive the box** as the tight box of the thresholded mask, using the identical definition
   as `tools/pack_dataset.py`, so RealSense and smartphone ground truth are generated by one
   rule and the cross-camera comparison is not confounded by a labelling difference.
4. **Emit a QC contact sheet** (`qc/`) with every mask overlaid and every automatic decision
   flagged against the RealSense reference statistics (`01_DATA.md`): hand area 1.6-4.7 % of the
   image, box aspect ~0.76, centre near (0.45, 0.49), border contact rare. Frames outside those
   bands are marked for manual attention rather than silently accepted.
5. **Accept manual corrections** from a small JSON: a click point to re-prompt, an explicit box,
   or a replacement mask PNG path. Re-run and the corrections are applied.

Nothing here is part of the model. It is annotation tooling, which the brief explicitly
sanctions (LSA p6 "you could use the annotation guide provided in coursework 1 release").

Usage
-----
    python tools/annotate_smartphone.py --videos smartphone_dataset/raw_videos \\
        --out smartphone_dataset/18006111_Shihab --backend grabcut
    # inspect smartphone_dataset/18006111_Shihab/../qc/contact_sheet_*.png, write corrections.json
    python tools/annotate_smartphone.py ... --corrections corrections.json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import cv2
import numpy as np

cv2.setNumThreads(1)          # see src/dataloader.py: cv2's pool is not fork-safe

GESTURES = ["G01_call", "G02_dislike", "G03_like", "G04_ok", "G05_one",
            "G06_palm", "G07_peace", "G08_rock", "G09_stop", "G10_three"]
GESTURE_SET = set(GESTURES)
NAME_RE = re.compile(r"^(G\d{2}_[A-Za-z]+)_?(clip\d{2})\.(mp4|mov|m4v|avi)$", re.IGNORECASE)

# Reference bands from the RealSense release (01_DATA.md s2), used only to FLAG proposals.
REF = {"area_lo": 0.010, "area_hi": 0.075, "aspect_lo": 0.35, "aspect_hi": 1.60,
       "cx_lo": 0.15, "cx_hi": 0.85, "cy_lo": 0.15, "cy_hi": 0.85}
MASK_THRESH = 128


# ======================================================================================
# frame sampling
# ======================================================================================
def sharpness(img: np.ndarray) -> float:
    """Variance of the Laplacian — the standard cheap focus measure."""
    return float(cv2.Laplacian(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), cv2.CV_64F).var())


def sample_frames(path: Path, n: int = 3, min_gap_s: float = 1.0) -> list[tuple[int, np.ndarray]]:
    """Pick ``n`` frames at least ``min_gap_s`` apart, each the sharpest in its window.

    The clip is split into ``n`` equal windows and the sharpest frame of each is taken. That
    guarantees the spacing rule by construction (windows of a >=3 s clip are >=1 s wide) while
    still avoiding blur, which a fixed-stride sampler would walk straight into.
    """
    cap = cv2.VideoCapture(str(path))
    if not cap.isOpened():
        raise RuntimeError(f"cannot open {path}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    frames = []
    idx = 0
    while True:
        ok, f = cap.read()
        if not ok:
            break
        frames.append((idx, f))
        idx += 1
    cap.release()
    if not frames:
        raise RuntimeError(f"no frames decoded from {path}")
    total = len(frames)
    if total / fps < min_gap_s * (n - 1):
        print(f"[warn] {path.name}: {total / fps:.2f}s is shorter than the {min_gap_s * (n - 1):.0f}s "
              f"the {n}-frame spacing rule needs", file=sys.stderr)

    picks = []
    bounds = np.linspace(0, total, n + 1).astype(int)
    for a, b in zip(bounds[:-1], bounds[1:]):
        window = frames[a:max(a + 1, b)]
        best = max(window, key=lambda t: sharpness(t[1]))
        picks.append(best)
    return picks


def centre_crop_43(img: np.ndarray) -> np.ndarray:
    """Centre-crop to 4:3 if the frame is wider, so phone 16:9 matches the RealSense aspect.

    Width-only crop, which is why the recording guide's framing rule is expressed in terms of
    frame *height*: the height rule survives the crop untouched.
    """
    h, w = img.shape[:2]
    target_w = int(round(h * 4 / 3))
    if w <= target_w:
        return img
    x0 = (w - target_w) // 2
    return img[:, x0:x0 + target_w]


# ======================================================================================
# mask proposal backends
# ======================================================================================
def skin_prior(bgr: np.ndarray) -> np.ndarray:
    """Loose skin-chroma likelihood in YCrCb — a seed, never the final mask.

    Deliberately permissive: the job is to give GrabCut a foreground seed that is mostly hand,
    not to segment the hand. A tight threshold tuned on one skin tone would bias the test set,
    which is exactly the sort of thing the cross-camera experiment must not smuggle in.
    """
    ycrcb = cv2.cvtColor(bgr, cv2.COLOR_BGR2YCrCb)
    cr, cb = ycrcb[..., 1].astype(np.int16), ycrcb[..., 2].astype(np.int16)
    m = ((cr >= 130) & (cr <= 180) & (cb >= 77) & (cb <= 135)).astype(np.uint8)
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    return cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((11, 11), np.uint8))


def largest_component(mask: np.ndarray) -> np.ndarray:
    n, lab, stats, _ = cv2.connectedComponentsWithStats((mask > 0).astype(np.uint8), 8)
    if n <= 1:
        return np.zeros_like(mask, np.uint8)
    k = 1 + int(np.argmax(stats[1:, cv2.CC_STAT_AREA]))
    return ((lab == k).astype(np.uint8)) * 255


def _rect_grabcut(bgr: np.ndarray, rect, iters: int = 5) -> np.ndarray:
    """GrabCut initialised from a rectangle. The fallback that cannot fail for lack of samples."""
    gc = np.zeros(bgr.shape[:2], np.uint8)
    bgd, fgd = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)
    try:
        cv2.grabCut(bgr, gc, tuple(int(v) for v in rect), bgd, fgd, iters, cv2.GC_INIT_WITH_RECT)
    except cv2.error:
        m = np.zeros(bgr.shape[:2], np.uint8)
        x, y, w, h = (int(v) for v in rect)
        m[y:y + h, x:x + w] = 255
        return m
    return np.where((gc == cv2.GC_FGD) | (gc == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)


def propose_grabcut(bgr: np.ndarray, point: tuple[int, int] | None = None,
                    iters: int = 5) -> np.ndarray:
    """Skin seed -> GrabCut -> largest component. No model download required.

    Three guards, each of which fired during testing:

    * **The skin seed is only trusted when it is plausibly hand-sized.** On a background whose
      chroma happens to sit in the skin band the seed can cover the whole frame; the reference
      distribution says a hand is 1-7.5% of the image, so a seed outside [0.2%, 35%] is discarded
      and a centre rectangle is used instead. A seed that covers everything is not a weak signal,
      it is *no* signal, and treating it as one produces a full-frame "hand".
    * **A border ring is always marked sure-background**, unconditionally. `cv2.grabCut` asserts
      on an empty background sample set, so a mask init with no definite background crashes.
    * **A result covering more than half the frame is rejected** in favour of the rectangle
      variant, and if that also fails the frame is left for manual correction rather than shipped.
    """
    h, w = bgr.shape[:2]
    npix = float(h * w)
    centre_rect = (int(w * 0.25), int(h * 0.15), int(w * 0.50), int(h * 0.70))

    seed = largest_component(skin_prior(bgr) * 255)
    frac = float((seed > 0).sum()) / npix
    if not (0.002 <= frac <= 0.35):
        seed = np.zeros((h, w), np.uint8)
        if point is not None:
            cv2.circle(seed, point, max(10, min(h, w) // 12), 255, -1)
        else:
            x, y, rw, rh = centre_rect
            seed[y:y + rh, x:x + rw] = 255
    elif point is not None:
        cv2.circle(seed, point, max(8, min(h, w) // 25), 255, -1)

    gc = np.full((h, w), cv2.GC_PR_BGD, np.uint8)
    sure_fg = cv2.erode(seed, np.ones((15, 15), np.uint8))
    probable = cv2.dilate(seed, np.ones((35, 35), np.uint8))
    gc[probable > 0] = cv2.GC_PR_FGD
    if sure_fg.sum() == 0:                       # erosion can annihilate a thin seed
        sure_fg = seed
    gc[sure_fg > 0] = cv2.GC_FGD
    ring = np.zeros((h, w), np.uint8)
    b = max(6, min(h, w) // 40)
    ring[:b, :] = ring[-b:, :] = ring[:, :b] = ring[:, -b:] = 1
    gc[ring > 0] = cv2.GC_BGD                    # unconditional: grabCut needs bgd samples

    out = None
    if (gc == cv2.GC_FGD).any() and (gc == cv2.GC_BGD).any():
        bgd, fgd = np.zeros((1, 65), np.float64), np.zeros((1, 65), np.float64)
        try:
            cv2.grabCut(bgr, gc, None, bgd, fgd, iters, cv2.GC_INIT_WITH_MASK)
            out = np.where((gc == cv2.GC_FGD) | (gc == cv2.GC_PR_FGD), 255, 0).astype(np.uint8)
        except cv2.error as e:
            print(f"[warn] mask-init grabCut failed ({str(e).splitlines()[-1][:70]}); "
                  f"retrying from a rectangle", file=sys.stderr)

    if out is None or float((out > 0).sum()) / npix > 0.5:
        rect = centre_rect
        if point is not None:
            rw, rh = int(w * 0.34), int(h * 0.52)
            rect = (max(0, point[0] - rw // 2), max(0, point[1] - rh // 2), rw, rh)
        out = _rect_grabcut(bgr, rect, iters)

    out = cv2.morphologyEx(out, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    out = cv2.morphologyEx(out, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))
    return largest_component(out)


_SAM = {}


def propose_sam(bgr: np.ndarray, ckpt: str, point: tuple[int, int] | None = None) -> np.ndarray:
    """Segment Anything with a point prompt, best of the three returned masks under a hand prior.

    Loaded lazily and cached: the encoder is the expensive part and 60 frames would otherwise
    pay for it 60 times.
    """
    if "predictor" not in _SAM:
        from segment_anything import SamPredictor, sam_model_registry   # optional dependency
        import torch
        kind = "vit_h" if "vit_h" in ckpt else "vit_l" if "vit_l" in ckpt else "vit_b"
        sam = sam_model_registry[kind](checkpoint=ckpt)
        sam.to("cuda" if torch.cuda.is_available() else "cpu")
        _SAM["predictor"] = SamPredictor(sam)
    pred = _SAM["predictor"]
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    pred.set_image(rgb)
    h, w = bgr.shape[:2]
    if point is None:
        sk = skin_prior(bgr)
        ys, xs = np.nonzero(largest_component(sk * 255))
        point = (int(xs.mean()), int(ys.mean())) if xs.size else (w // 2, h // 2)
    masks, scores, _ = pred.predict(point_coords=np.array([point]),
                                    point_labels=np.array([1]), multimask_output=True)
    best, best_s = None, -1e9
    for m, s in zip(masks, scores):
        mm = (m.astype(np.uint8)) * 255
        sc = float(s) + hand_prior_score(mm)
        if sc > best_s:
            best, best_s = mm, sc
    return largest_component(best)


def hand_prior_score(mask: np.ndarray) -> float:
    """Reward proposals that look like the RealSense hand distribution; penalise the rest.

    SAM's own score prefers 'a confident object', which on a hand-and-forearm image is often the
    whole arm. This term is what stops the arm winning.
    """
    h, w = mask.shape
    box = mask_to_box(mask)
    if box is None:
        return -10.0
    x1, y1, x2, y2 = box
    area = float((mask > 0).sum()) / (h * w)
    bw, bh = max(x2 - x1, 1), max(y2 - y1, 1)
    aspect = bw / bh
    cx, cy = (x1 + x2) / 2 / w, (y1 + y2) / 2 / h
    s = 0.0
    s -= 6.0 * max(0.0, REF["area_lo"] - area) / REF["area_lo"]
    s -= 6.0 * max(0.0, area - REF["area_hi"]) / REF["area_hi"]
    s -= 2.0 * max(0.0, REF["aspect_lo"] - aspect) - 2.0 * max(0.0, aspect - REF["aspect_hi"])
    s -= 2.0 * (abs(cx - 0.45) + abs(cy - 0.49))
    fill = float((mask > 0).sum()) / (bw * bh)
    s -= 2.0 * max(0.0, 0.30 - fill)      # a hand fills ~49% of its box; 0.15 means an arm
    return s


def mask_to_box(mask: np.ndarray) -> list[float] | None:
    ys, xs = np.nonzero(mask >= MASK_THRESH)
    if xs.size == 0:
        return None
    return [float(xs.min()), float(ys.min()), float(xs.max() + 1), float(ys.max() + 1)]


# ======================================================================================
# QC
# ======================================================================================
def qc_flags(mask: np.ndarray) -> list[str]:
    h, w = mask.shape
    flags = []
    box = mask_to_box(mask)
    if box is None:
        return ["EMPTY_MASK"]
    x1, y1, x2, y2 = box
    area = float((mask > 0).sum()) / (h * w)
    bw, bh = max(x2 - x1, 1), max(y2 - y1, 1)
    if area < REF["area_lo"]:
        flags.append(f"TOO_SMALL({area * 100:.1f}%)")
    if area > REF["area_hi"]:
        flags.append(f"TOO_LARGE({area * 100:.1f}%)")
    ar = bw / bh
    if not REF["aspect_lo"] <= ar <= REF["aspect_hi"]:
        flags.append(f"ASPECT({ar:.2f})")
    cx, cy = (x1 + x2) / 2 / w, (y1 + y2) / 2 / h
    if not (REF["cx_lo"] <= cx <= REF["cx_hi"] and REF["cy_lo"] <= cy <= REF["cy_hi"]):
        flags.append(f"OFF_CENTRE({cx:.2f},{cy:.2f})")
    if x1 <= 1 or y1 <= 1 or x2 >= w - 1 or y2 >= h - 1:
        flags.append("TOUCHES_BORDER")
    n, _, stats, _ = cv2.connectedComponentsWithStats((mask > 0).astype(np.uint8), 8)
    big = [s for s in stats[1:, cv2.CC_STAT_AREA] if s > 0.005 * h * w]
    if len(big) > 1:
        flags.append(f"MULTI_COMPONENT({len(big)})")
    fill = float((mask > 0).sum()) / (bw * bh)
    if fill < 0.30:
        flags.append(f"LOW_FILL({fill:.2f})")
    return flags


def overlay(bgr: np.ndarray, mask: np.ndarray) -> np.ndarray:
    out = bgr.copy()
    col = np.zeros_like(out)
    col[..., 1] = 255
    m = (mask >= MASK_THRESH)
    out[m] = (0.55 * out[m] + 0.45 * col[m]).astype(np.uint8)
    cnts, _ = cv2.findContours((m).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(out, cnts, -1, (0, 200, 90), 2)
    box = mask_to_box(mask)
    if box:
        x1, y1, x2, y2 = (int(v) for v in box)
        cv2.rectangle(out, (x1, y1), (x2, y2), (0, 215, 255), 2)
    return out


def contact_sheet(items: list[dict], out_path: Path, cols: int = 6, tile: int = 260) -> None:
    rows = int(np.ceil(len(items) / cols))
    sheet = np.full((rows * (tile + 26), cols * tile, 3), 245, np.uint8)
    for i, it in enumerate(items):
        r, c = divmod(i, cols)
        img = cv2.resize(it["overlay"], (tile, tile))
        y0, x0 = r * (tile + 26), c * tile
        sheet[y0 + 26:y0 + 26 + tile, x0:x0 + tile] = img
        bad = bool(it["flags"])
        cv2.rectangle(sheet, (x0, y0), (x0 + tile - 1, y0 + 25),
                      (60, 60, 220) if bad else (230, 230, 230), -1)
        cv2.putText(sheet, it["id"], (x0 + 4, y0 + 11), cv2.FONT_HERSHEY_SIMPLEX, 0.33,
                    (255, 255, 255) if bad else (30, 30, 30), 1, cv2.LINE_AA)
        cv2.putText(sheet, (",".join(it["flags"])[:44] or "ok"), (x0 + 4, y0 + 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.31,
                    (255, 255, 255) if bad else (60, 120, 60), 1, cv2.LINE_AA)
        if bad:
            cv2.rectangle(sheet, (x0, y0 + 26), (x0 + tile - 1, y0 + 25 + tile), (60, 60, 220), 3)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out_path), sheet)


# ======================================================================================
# main
# ======================================================================================
def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--videos", required=True, help="flat folder of 20 clips, G01_call_clip01.mov")
    ap.add_argument("--out", required=True, help="smartphone_dataset/<studentno>_<surname>")
    ap.add_argument("--backend", choices=["grabcut", "sam"], default="grabcut")
    ap.add_argument("--sam-ckpt", default=None)
    ap.add_argument("--frames-per-clip", type=int, default=3)
    ap.add_argument("--min-gap-s", type=float, default=1.0)
    ap.add_argument("--crop-43", action="store_true", default=True)
    ap.add_argument("--no-crop-43", dest="crop_43", action="store_false")
    ap.add_argument("--corrections", default=None,
                    help='JSON: {"G01_call/clip01/002": {"point":[x,y]} | {"mask":"path.png"} '
                         '| {"box":[x1,y1,x2,y2]} | {"drop":true}}')
    ap.add_argument("--qc-dir", default=None)
    a = ap.parse_args(argv)

    vids = sorted(p for p in Path(a.videos).iterdir()
                  if p.is_file() and NAME_RE.match(p.name))
    if not vids:
        print(f"[error] no correctly-named clips in {a.videos}. Expected G01_call_clip01.mov etc.",
              file=sys.stderr)
        return 2
    corrections = json.loads(Path(a.corrections).read_text()) if a.corrections else {}
    out_root = Path(a.out)
    qc_dir = Path(a.qc_dir) if a.qc_dir else out_root.parent / "qc"
    sheet_items, index, n_flagged = [], [], 0

    for v in vids:
        m = NAME_RE.match(v.name)
        gesture, clip = m.group(1), m.group(2).lower()
        if gesture not in GESTURE_SET:
            print(f"[warn] {v.name}: unknown gesture {gesture}, skipped", file=sys.stderr)
            continue
        picks = sample_frames(v, a.frames_per_clip, a.min_gap_s)
        for j, (fi, frame) in enumerate(picks, start=1):
            if a.crop_43:
                frame = centre_crop_43(frame)
            key = f"{gesture}/{clip}/{j:03d}"
            corr = corrections.get(key, {})
            if corr.get("drop"):
                print(f"[skip] {key} dropped by corrections file")
                continue

            if "mask" in corr:
                mask = cv2.imread(corr["mask"], cv2.IMREAD_GRAYSCALE)
                mask = np.where(mask >= MASK_THRESH, 255, 0).astype(np.uint8)
            elif "box" in corr:
                x1, y1, x2, y2 = (int(t) for t in corr["box"])
                mask = np.zeros(frame.shape[:2], np.uint8)
                mask[y1:y2, x1:x2] = 255
            else:
                pt = tuple(corr["point"]) if "point" in corr else None
                if a.backend == "sam":
                    if not a.sam_ckpt:
                        print("[error] --backend sam needs --sam-ckpt", file=sys.stderr)
                        return 2
                    mask = propose_sam(frame, a.sam_ckpt, pt)
                else:
                    mask = propose_grabcut(frame, pt)

            flags = qc_flags(mask)
            n_flagged += bool(flags)
            box = mask_to_box(mask)

            cdir = out_root / gesture / clip
            (cdir / "rgb").mkdir(parents=True, exist_ok=True)
            (cdir / "annotation").mkdir(parents=True, exist_ok=True)
            cv2.imwrite(str(cdir / "rgb" / f"frame_{j:03d}.png"), frame)
            cv2.imwrite(str(cdir / "annotation" / f"frame_{j:03d}.png"), mask)

            sheet_items.append({"id": key, "flags": flags, "overlay": overlay(frame, mask)})
            index.append({"id": key, "gesture": gesture, "clip": clip, "frame": j,
                          "source_video": v.name, "source_frame_index": int(fi),
                          "box": box, "flags": flags,
                          "size": [int(frame.shape[1]), int(frame.shape[0])],
                          "backend": ("manual" if ("mask" in corr or "box" in corr)
                                      else a.backend)})
            print(f"[ann] {key:26s} {'FLAG ' + ','.join(flags) if flags else 'ok'}")

    qc_dir.mkdir(parents=True, exist_ok=True)
    for i in range(0, len(sheet_items), 30):
        contact_sheet(sheet_items[i:i + 30], qc_dir / f"contact_sheet_{i // 30 + 1:02d}.png")
    (qc_dir / "annotation_index.json").write_text(json.dumps(index, indent=1))

    # The brief asks for a bounding box "derived from the mask" as part of the dataset itself,
    # so the boxes belong INSIDE the student folder that is handed in -- not only in the QC
    # sidecar, which is working material and is not part of the submitted dataset. The masks
    # remain the source of truth; boxes.json is the derived view, written next to them so a
    # reader does not have to re-derive it to check the annotation.
    boxes = {r["id"]: {"box": r["box"], "gesture": r["gesture"], "clip": r["clip"],
                       "frame": r["frame"], "size": r["size"]} for r in index}
    (out_root / "boxes.json").write_text(json.dumps(
        {"convention": "(x1,y1,x2,y2) absolute pixels, tight box of the mask thresholded at 128; "
                       "x2/y2 are one past the last foreground pixel, matching "
                       "src/utils.mask_to_box and tools/pack_dataset.py",
         "n": len(boxes), "boxes": boxes}, indent=1))

    print(f"\n[ann] {len(index)} frames written to {out_root} (+ boxes.json)")
    print(f"[ann] {n_flagged} flagged for manual review -> {qc_dir}/contact_sheet_*.png")
    if len(index) != 60:
        print(f"[ann] WARNING: the brief asks for 60 frames (10 gestures x 2 clips x 3), got "
              f"{len(index)}", file=sys.stderr)
    missing = sorted(GESTURE_SET - {r['gesture'] for r in index})
    if missing:
        print(f"[ann] WARNING: no clips found for {missing}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
